#!/usr/bin/env python3
# gdpRawData.py - Extract life expectancy data from world bank website.
# Source API Documentation - https://pypi.org/project/wbgapi/

#Modules
import wbgapi as wb
import pandas as pd

#Set Values
gdp_id = 'NY.GDP.MKTP.CD'
countryCodes = ['USA', 'CAN', 'CHN', 'AUS'] #leave '' for all countries.
timePeriod = '10' #leave blank for all years.  For .fetch function only.

#Extracting Data Functions - 
    #wb.data.fetch() - This function returns rows as dictionaries.
    #wb.data.DataFrame() - This function returns rows as a pandas DF.
    #fetch Arguments - (['ID1', 'ID2'....], 'Country Code, mrv='Number of Years')
    #DF Arguments - (['ID1', 'ID2'....], 'Country Code, time='Number of Years, skipBlanks=True, columns='time/series/economy').reset_index() which replaces the index with 0-based integers

    #.fetch function:
#for series in wb.data.fetch(gdp_id, countryCodes, mrv=timePeriod):
    #print(series)

    #.DataFrame function:
gdpDF = wb.data.DataFrame(gdp_id, countryCodes, time=range(1960,2023), skipBlanks=True, columns='time').reset_index()
numericColumns = gdpDF.select_dtypes(include='number').columns
gdpDF[numericColumns] = gdpDF[numericColumns].div(10**9) #Divide by 1 billion.
gdpDF = gdpDF.round(1)
print(gdpDF)
